### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by fmoessbauer** [ska-telescope/cpp_build_base#2]
Hi, could you please add a license, so I can re-use parts of this (mainly ctest2junit.xsl) this in my projects?

**Comment by rtobar** [comment]
The `ctest2junit.xsl` file is not of our authorship originally; I can't remember where I got it from orignally, but sadly I didn't take notice of the original license. If you google the name though you'll find several references, up to 2011 which seems to be where the original code was written: https://stackoverflow.com/questions/6329215/how-to-get-ctest-results-in-hudson-jenkins. The files there have no llicense, so I'd assume some default SO licensing (CC?) applies.

I'd recommend taking things from the historical sites rather than here, where we simply put a couple of files together. Please also note this repo in GitHub is simply a mirror from the correspnding one in GitLab, so issues here won't necessarily be seen/acted upon.
